[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:railway"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "3001"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
JWT_SECRET = "your-secure-production-jwt-secret-key-change-this"